spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dddandeda
    username: postgres
    password: password
  jpa:
    database: postgresql
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      platform: postgres
      mode: always